export { default as Navbar} from './Navbar/Navbar';
export { default as Hero } from './reusable/Hero/Hero';
export { default as Sponsor} from './Sponsor/Sponsor';
export { default as Product} from './Product/Product';
export { default as Newsletter} from './reusable/Newsletter/Newsletter';
export { default as Lector} from './Lector/Lector';
export { default as Footer} from './Footer/Footer';
export { default as ContactHero} from './ContactHero/ContactHero';
export { default as ContactPeople} from './ContactPeople/ContactPeople';
export { default as ContactBank} from './ContactBank/ContactBank';
export { default as References} from './References/References';
export { default as Info} from './reusable/Info/Info';
export { default as InfoCards} from './reusable/InfoCards/InfoCards';
export { default as Student} from './reusable/Student/Student';
export { default as Questions} from './reusable/Questions/Questions';
export { default as Program} from './Program/Program';
export { default as AboutHero} from './AboutHero/AboutHero';
export { default as AboutProduct} from './AboutProduct/AboutProduct';
export { default as Gallery} from './Gallery/Gallery';
export { default as Thanks} from './Thanks/Thanks';
export { default as Price } from './reusable/Price/Price';
export { default as Process} from './reusable/Process/Process';
export { default as AboutMore} from './AboutMore/AboutMore';
export { default as SocialMobile} from './SocialMobile/SocialMobile';